### ISSUE TITLE
Why are you a bad person for using Regex over an AST?

### ISSUE THREAD

**Issue by thejameskyle** [jdalton/ama#16]

**Comment by megawac** [comment]
I think this should be settled in an official fisty cuff match at the next JSConf

**Comment by thejameskyle** [comment]
:facepunch:

**Comment by jdalton** [comment]
>  or you know jdalton could just give it up

![no](https://cloud.githubusercontent.com/assets/4303/8641747/c375197a-28ce-11e5-9dea-c58065194edf.gif)

**Comment by thejameskyle** [comment]
:v:
