### ISSUE TITLE
Lodash src is pretty hard to read for beginners. What's the entry point for them to read?

### ISSUE THREAD

**Issue by stevemao** [jdalton/ama#19]

**Comment by jdalton** [comment]
I donno some folks [seem](https://twitter.com/kemaalmaulana/status/612642771917144065) to [dig](https://twitter.com/jackgardner88/status/605461033046712321) it. Just jump in, there's plenty of code comments to explain things. If you have questions you can pop on over to our [gitter chat](https://gitter.im/lodash/lodash) and someone will help you out.
